version: "3.8"
services:
  app:
    build: .
    command: python main.py
    environment:
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    ports:
      - "8080:8080"
    volumes:
      - .:/python-flask
