apiVersion: v1
kind: Secret
metadata:
  name: lightcurve-s3
data:
  {{- if .Values.lightcurve_s3 }}
  {{- if .Values.lightcurve_s3.S3_ACCESS_KEY_ID }}
  S3_ACCESS_KEY_ID: {{ .Values.lightcurve_s3.S3_ACCESS_KEY_ID | b64enc }}
  {{- end }}
  {{- if .Values.lightcurve_s3.S3_SECRET_ACCESS_KEY }}
  S3_SECRET_ACCESS_KEY: {{ .Values.lightcurve_s3.S3_SECRET_ACCESS_KEY | b64enc }}
  {{- end }}
  {{- end }}
